server:
  port: 9000

spring:
  application:
    name: my-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: my-service
    qos-port: 22222
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 15511