server:
  port: 9002

spring:
  application:
    name: my-service-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: my-service-api
    qos-port: 22223
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 15512