server:
  port: 9001

spring:
  application:
    name: other-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: other-service
    qos-port: 22223
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 15512